# Generated by Django 5.2.12 on 2026-04-08 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-yaratilgan_sana']},
        ),
        migrations.AlterField(
            model_name='post',
            name='sarlavha',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-yaratilgan_sana', 'nashr_etilgan'], name='blog_post_yaratil_7b945e_idx'),
        ),
    ]
